import { Router, type IRouter } from "express";
import healthRouter from "./health";
import patientsRouter from "./patients";
import recordsRouter from "./records";
import interpretationsRouter from "./interpretations";
import gaugesRouter from "./gauges";
import alertsRouter from "./alerts";
import dashboardRouter from "./dashboard";
import { biomarkerResultsRouter, biomarkerReferenceRouter } from "./biomarkers";
import supplementsRouter from "./supplements";
import biologicalAgeRouter from "./biological-age";
import correlationsRouter from "./correlations";
import baselinesRouter from "./baselines";
import notesRouter from "./notes";
import alertPrefsRouter from "./alert-prefs";
import accountRouter from "./account";
import chatRouter from "./chat";
import predictionsRouter from "./predictions";
import shareRouter, { publicRouter as sharePublicRouter } from "./share";
import protocolsRouter, { globalRouter as protocolsGlobalRouter } from "./protocols";
import reportsRouter from "./reports";
import storageRouter from "./storage";
import geneticsRouter, { globalRouter as pgsCatalogRouter } from "./genetics";
import imagingRouter, { dicomRouter } from "./imaging";
import complianceRouter from "./compliance";
import adminRouter from "./admin";
import wearablesRouter, { wearablesPatientRouter } from "./wearables";
import trendsRouter from "./trends";
import safetyRouter from "./safety";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/patients", patientsRouter);
router.use("/patients/:patientId/records", recordsRouter);
router.use("/patients/:patientId/interpretations", interpretationsRouter);
router.use("/patients/:patientId/gauges", gaugesRouter);
router.use("/patients/:patientId/alerts", alertsRouter);
router.use("/patients/:patientId/dashboard", dashboardRouter);
router.use("/patients/:patientId/biomarkers", biomarkerResultsRouter);
router.use("/patients/:patientId/supplements", supplementsRouter);
router.use("/patients/:patientId/biological-age", biologicalAgeRouter);
router.use("/patients/:patientId/correlations", correlationsRouter);
router.use("/patients/:patientId/baselines", baselinesRouter);
router.use("/patients/:patientId/notes", notesRouter);
router.use("/patients/:patientId/alert-preferences", alertPrefsRouter);
router.use("/patients/:patientId/chat", chatRouter);
router.use("/patients/:patientId/predictions", predictionsRouter);
router.use("/patients/:patientId/share-links", shareRouter);
router.use("/patients/:patientId/protocols", protocolsRouter);
router.use("/patients/:patientId/reports", reportsRouter);
router.use("/biomarker-reference", biomarkerReferenceRouter);
router.use("/protocols", protocolsGlobalRouter);
router.use("/me", accountRouter);
router.use("/me", complianceRouter);
router.use("/share", sharePublicRouter);
router.use("/admin", adminRouter);
router.use("/patients/:patientId/genetics", geneticsRouter);
router.use("/patients/:patientId/imaging", imagingRouter);
router.use("/patients/:patientId", geneticsRouter); // also exposes /patients/:pid/prs
router.use(pgsCatalogRouter);
router.use(dicomRouter);
router.use(storageRouter);
router.use("/me", wearablesRouter);
router.use("/patients/:patientId/wearables", wearablesPatientRouter);
router.use("/patients/:patientId/trends", trendsRouter);
router.use("/patients/:patientId/safety", safetyRouter);

export default router;
